### ISSUE TITLE
现在一天最多30分了，猴年马月才能够。。。

### ISSUE THREAD

**Issue by liuyanhang2004** [huaisha1224/Microsoft-Rewards#1]

**Comment by huaisha1224** [comment]
你的等级到2的时候 就可以90积分了，先升级一下就可以了

**Comment by huaisha1224** [comment]
建议使用我的油猴脚本，跑起来更方便一些
https://greasyfork.org/zh-CN/scripts/477107-microsoft-bing-rewards%E6%AF%8F%E6%97%A5%E4%BB%BB%E5%8A%A1%E8%84%9A%E6%9C%AC
