### ISSUE TITLE
手机版脚本出现问题

### ISSUE THREAD

**Issue by qingting04** [huaisha1224/Microsoft-Rewards#3]
开启脚本后，出现Ref A: 635F796F3AFE482BB871271E32ECAB54 Ref B: BJ1EDGE0920 Ref C: 2024-05-23T05:49:50Z，可能是重定向过多

**Comment by qingting04** [comment]
应该不是插件的问题，现在在贴吧中，有大量该问题复现

**Comment by huaisha1224** [comment]
这个问题其实是微软服务器的原因
